name: molecule_parser
description: Parser/generator for common chemical file formats.
version: 0.0.1
repository: https://github.com/afstanton/molecule_parser

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  molecule_core: ^0.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
